const preguntasAnimales = [
  { q: "Los perros pertenecen al grupo de los mamíferos.", a: true },
  { q: "Los gatos son carnívoros por naturaleza.", a: true },
  { q: "Los canguros llevan a sus crías en una bolsa en su panza.", a: true },
  { q: "Los delfines son mamíferos acuáticos.", a: true },
  { q: "Las ballenas azules son los animales más grandes del planeta.", a: true },
  { q: "Los murciélagos son los únicos mamíferos capaces de volar.", a: true },
  { q: "Las vacas son animales herbívoros porque comen hierba.", a: true },
  { q: "Las jirafas tienen el cuello corto.", a: false },
  { q: "Los leones viven en el Polo Norte entre la nieve.", a: false },
  { q: "Los osos polares tienen la piel de color rosado.", a: false },
  { q: "Las ballenas mamantan a sus crías con leche materna.", a: true },
  { q: "Los elefantes son los animales terrestres más grandes del mundo.", a: true },
  { q: "Los guepardos son los animales terrestres más rápidos del mundo.", a: true },
  { q: "Los conejos nacen de huevos blandos.", a: false },
  { q: "Los perros son animales ovíparos que nacen de un huevo.", a: false },
  { q: "Los koalas se alimentan principalmente de hojas de eucalipto.", a: true },
  { q: "Los hipopótamos pasan gran parte del día dentro del agua.", a: true },
  { q: "Los caballos son carnívoros y cazan otros animales.", a: false },
  { q: "Los cerdos tienen una excelente memoria y son muy inteligentes.", a: true },
  { q: "Los zorros pertenecen a la familia de los caninos.", a: true },
  { q: "Los tigres tienen rayas en la piel y no solo en el pelo.", a: true },
  { q: "Los rinocerontes tienen uno o dos cuernos en el hocico.", a: true },
  { q: "Los perezosos son animales que se mueven muy rápido por los árboles.", a: false },
  { q: "Los murciélagos usan el eco de sus sonidos para orientarse de noche.", a: true },
  { q: "Los ornitorrincos son mamíferos que nacen de huevos.", a: true },
  { q: "Los camellos pueden pasar varios días sin beber agua.", a: true },
  { q: "La joroba del camello almacena agua como una botella.", a: false },
  { q: "Las cebras son parientes cercanos de los caballos.", a: true },
  { q: "Los gorilas son los primates más grandes del planeta.", a: true },
  { q: "Los lobos viven en grupos llamados manadas.", a: true },
  { q: "Los osos panda comen principalmente tallos de bambú.", a: true },
  { q: "Los gatos pueden ver muy bien con poca luz nocturna.", a: true },
  { q: "Las ovejas nos dan lana para fabricar ropa de abrigo.", a: true },
  { q: "Los hámsteres guardan comida en las bolsas de sus mejillas.", a: true },
  { q: "Los castores construyen presas de madera en los ríos.", a: true },
  { q: "Los leones marinos tienen aletas y son mamíferos.", a: true },
  { q: "Los chimpancés pueden usar herramientas simples como palos y piedras.", a: true },
  { q: "Los leopardos son excelentes trepadores de árboles.", a: true },
  { q: "Los venados o ciervos pierden sus astas y les vuelven a crecer cada año.", a: true },
  { q: "Los zorros polares cambian el color de su pelaje según la estación del año.", a: true },
  { q: "Los pingüinos son aves que saben volar en el cielo.", a: false },
  { q: "Todas las aves tienen el cuerpo cubierto de plumas.", a: true },
  { q: "Todas las aves nacen de huevos.", a: true },
  { q: "Los avestruces son aves gigantes que no pueden volar.", a: true },
  { q: "Los colibríes son las únicas aves que pueden volar hacia atrás.", a: true },
  { q: "Los búhos pueden girar la cabeza casi por completo.", a: true },
  { q: "Los loros pueden aprender a imitar palabras humanas.", a: true },
  { q: "Los patos tienen patas con membranas que les ayudan a nadar.", a: true },
  { q: "Los águilas tienen una visión muy deficiente y mala memoria.", a: false },
  { q: "Los flamencos son de color rosado por los alimentos que comen.", a: true },
  { q: "Los tucanes tienen un pico grande pero muy liviano.", a: true },
  { q: "Los gallos cantan por la mañana y son aves de corral.", a: true },
  { q: "Los pajaritos fabrican nidos para poner sus huevos y cuidar sus crías.", a: true },
  { q: "Los cisnes son aves acuáticas conocidas por su cuello largo.", a: true },
  { q: "Los carpinteros usan su pico para hacer agujeros en la madera de los árboles.", a: true },
  { q: "Las palomas son aves que viven en muchas ciudades del mundo.", a: true },
  { q: "Los buitres son aves carroñeras que comen animales muertos.", a: true },
  { q: "Los colibríes se alimentan del néctar de las flores.", a: true },
  { q: "Las gallinas son mamíferos que dan leche.", a: false },
  { q: "Los pavorreales machos abren su cola en forma de abanico colorido.", a: true },
  { q: "Los pelícanos tienen una gran bolsa en el pico para atrapar peces.", a: true },
  { q: "Los cigüeñas hacen nidos grandes en campanarios y postes altos.", a: true },
  { q: "Todas las aves migrate viajan hacia el norte durante el invierno frío.", a: false },
  { q: "Los búhos son aves cazadoras principalmente nocturnas.", a: true },
  { q: "El avestruz pone los huevos más grandes del mundo.", a: true },
  { q: "Los colibríes aletean muy rápido, cientos de veces por segundo.", a: true },
  { q: "Las gaviotas son aves que suelen verse cerca del mar y las costas.", a: true },
  { q: "El cóndor de los Andes es una de las aves voladoras más grandes.", a: true },
  { q: "Las aves tienen dientes afilados dentro de sus picos.", a: false },
  { q: "Los pingüinos usan sus alas como aletas para nadar debajo del agua.", a: true },
  { q: "Los periquitos son aves pequeñas y coloridas que viven en grupo.", a: true },
  { q: "El pavo real hembra es más colorida y brillante que el macho.", a: false },
  { q: "Las golondrinas viajan largas distancias al cambiar de estación.", a: true },
  { q: "Los kiwis son aves sin alas funcionales originarias de Nueva Zelanda.", a: true },
  { q: "Los halcones son las aves más rápidas al tirarse en picado.", a: true },
  { q: "El huevo de la gallina tiene una cáscara dura que protege al polluelo.", a: true },
  { q: "Los patos tienen plumas impermeables que repelen el agua.", a: true },
  { q: "Los cuervos son aves muy inteligentes capaces de resolver problemas.", a: true },
  { q: "Los guacamayos son loros grandes de colores muy vivos.", a: true },
  { q: "Las aves no tienen huesos, por eso son tan livianas.", a: false },
  { q: "Los cocodrilos son reptiles que nacen de huevos.", a: true },
  { q: "Las serpientes tienen patas largas para correr rápido.", a: false },
  { q: "Los camaleones pueden cambiar de color para camuflarse.", a: true },
  { q: "Los sapos y ranas son animales anfibios.", a: true },
  { q: "Las tortugas marinas ponen sus huevos en las playas de arena.", a: true },
  { q: "Los renacuajos son los bebés de las ranas y viven en el agua.", a: true },
  { q: "Las ranas pasan por un cambio llamado metamorfosis.", a: true },
  { q: "Todas las serpientes del mundo son venenosas.", a: false },
  { q: "Los iguanas son reptiles herbívoros que les gusta el sol.", a: true },
  { q: "Las tortugas de tierra son animales que se mueven muy rápido.", a: false },
  { q: "Las serpientes mudan su piel completa a medida que crecen.", a: true },
  { q: "Los reptiles son animales de sangre fría que necesitan el calor del sol.", a: true },
  { q: "Los caimanes y cocodrilos son excelentes nadadores.", a: true },
  { q: "Los geckos pueden caminar por las paredes y techos sin caerse.", a: true },
  { q: "Las salamandras son reptiles cubiertos de escamas duras.", a: false },
  { q: "Los anfibios tienen la piel húmeda y suave.", a: true },
  { q: "Las tortugas llevan su caparazón pegado a su cuerpo como protección.", a: true },
  { q: "El dragón de Komodo es el lagarto más grande del mundo.", a: true },
  { q: "Las serpientes no tienen párpados móviles y no pueden pestañear.", a: true },
  { q: "Las ranas pueden respirar a través de su piel húmeda.", a: true },
  { q: "Los caimanes tienen los dientes a la vista cuando cierran la boca.", a: true },
  { q: "Las tortugas terrestres pueden vivir más de 100 años.", a: true },
  { q: "Los anfibios nacen con branquias y luego desarrollan pulmones.", a: true },
  { q: "Las serpientes oyen ruidos altos a través de orejas gigantes.", a: false },
  { q: "Los camaleones pueden mover sus dos ojos en direcciones diferentes al mismo tiempo.", a: true },
  { q: "Las serpientes usan su lengua bífida para oler su entorno.", a: true },
  { q: "Los sapos tienen la piel más verrugosa y seca que las ranas.", a: true },
  { q: "El monstruo de Gila es uno de los pocos lagartos venenosos.", a: true },
  { q: "Las tortugas pueden quitarse el caparazón como si fuera una ropa.", a: false },
  { q: "Las serpientes pitón matan a sus presas envolviéndolas apretadamente.", a: true },
  { q: "Los reptiles tienen el cuerpo cubierto de plumas suaves.", a: false },
  { q: "Los sapos adultos comen insectos usando su lengua pegajosa.", a: true },
  { q: "El basilisco es un lagarto que puede correr sobre el agua un tramo corto.", a: true },
  { q: "Las ranas de cristal son transparentes y se ven sus órganos.", a: true },
  { q: "Los anfibios pueden vivir en desiertos secos sin nada de agua.", a: false },
  { q: "Los peces respiran oxígeno del aire con pulmones.", a: false },
  { q: "Los tiburones son peces con esqueletos de cartílago.", a: true },
  { q: "Los peces respiran oxígeno disuelto en el agua usando branquias.", a: true },
  { q: "Los pulpos tienen 3 corazones y sangre de color azul.", a: true },
  { q: "Los caballitos de mar son peces donde el papá lleva los huevos.", a: true },
  { q: "Las medusas tienen cerebro, corazón y huesos duros.", a: false },
  { q: "Los peces payaso viven protegidos entre los tentáculos de las anemonas.", a: true },
  { q: "Las estrellas de mar pueden regenerar un brazo si lo pierden.", a: true },
  { q: "Los cangrejos caminan hacia adelante de forma recta como las personas.", a: false },
  { q: "Los peces tienen escamas que cubren su cuerpo.", a: true },
  { q: "Los tiburones pierden y reemplazan miles de dientes durante su vida.", a: true },
  { q: "El pez globo se infla con agua o aire para parecer más grande ante el peligro.", a: true },
  { q: "Las calamares gigantes viven en las profundidades del océano.", a: true },
  { q: "Los peces abisales de las profundidades pueden producir su propia luz.", a: true },
  { q: "Los arrecifes de coral están formados por pequeños animales vivos.", a: true },
  { q: "Las almejas y mejillones son moluscos protegidos por dos conchas.", a: true },
  { q: "Los tiburones no tienen huesos de verdad, su esqueleto es de cartílago.", a: true },
  { q: "Los peces voladores pueden planear sobre el agua para escapar de los depredadores.", a: true },
  { q: "Las manta rayas son parientes de los tiburones.", a: true },
  { q: "Los pulpos expulsa tinta negra para distraer a sus enemigos y escapar.", a: true },
  { q: "Las ballenas expulsan aire y vapor de agua por un orificio llamado espiráculo.", a: true },
  { q: "Las langostas de mar tienen grandes pinzas para defenderse.", a: true },
  { q: "Los tiburones blancos son vegetarianos y solo comen algas marrones.", a: false },
  { q: "Los peces espada tienen un hocico largo y afilado como una espada.", a: true },
  { q: "Las mantarrayas nadan batiendo sus aletas como si estuvieran volando.", a: true },
  { q: "Las anguilas eléctricas pueden generar descargas para defenderse.", a: true },
  { q: "Los peces dorados tienen una memoria que dura solo 3 segundos.", a: false },
  { q: "Las esponjas de mar son plantas marinas que hacen fotosíntesis.", a: false },
  { q: "Las orcas son conocidas como las ballenas asesinas pero son en realidad delfines grandes.", a: true },
  { q: "Los peces respiran por los ojos.", a: false },
  { q: "Los tiburones martillo tienen los ojos a los lados de su cabeza ancha.", a: true },
  { q: "Los erizos de mar están cubiertos de espinas protectoras.", a: true },
  { q: "Las focas tienen una capa gruesa de grasa para protegerse del frío extremo.", a: true },
  { q: "Los mariscos como las gambas o camarones son peces con escamas.", a: false },
  { q: "El pez piedra es uno de los peces más venenosos del mundo.", a: true },
  { q: "Las arañas tienen 8 patas.", a: true },
  { q: "Las hormigas pueden levantar objetos más pesados que ellas.", a: true },
  { q: "Las abejas producen deliciosa miel en sus colmenas.", a: true },
  { q: "Los insectos tienen el cuerpo dividido en 3 partes: cabeza, tórax y abdomen.", a: true },
  { q: "Los insectos adultos tienen 6 patas.", a: true },
  { q: "Las arañas son insectos de 6 patas.", a: false },
  { q: "Las mariposas nacen siendo orugas que luego forman una crisálida.", a: true },
  { q: "Las mariquitas (o catarinas) son escarabajos de colores con puntos negros.", a: true },
  { q: "Los mosquitos machos son los que pican a las personas para chupar sangre.", a: false },
  { q: "Las luciérnagas pueden brillar en la oscuridad para comunicarse.", a: true },
  { q: "Los ciempiés tienen exactamente 100 patas en total.", a: false },
  { q: "Los saltamontes usan sus potentes patas traseras para dar grandes saltos.", a: true },
  { q: "Las abejas mueren generalmente después de picar con su aguijón.", a: true },
  { q: "Los caracoles llevan su casa a cuestas llamada concha.", a: true },
  { q: "Los lombrices de tierra ayudan a airear el suelo y hacerlo fértil.", a: true },
  { q: "Las arañas tejen redes de seda para atrapar su comida.", a: true },
  { q: "Las moscas tienen 2 alas y ven a través de ojos compuestos enormes.", a: true },
  { q: "Los escorpiones tienen un aguijón con veneno en el extremo de la cola.", a: true },
  { q: "Las hormigas reinas son las encargadas de poner los huevos en la colonia.", a: true },
  { q: "Las mariposas prueban el sabor de las plantas con sus patas.", a: true },
  { q: "Las polillas suelen ser atraídas por la luz durante la noche.", a: true },
  { q: "Las avispas construyen nidos de papel o barro.", a: true },
  { q: "Los ciempiés y milpiés pertenecen al grupo de los insectos.", a: false },
  { q: "Las arañas no tienen antenas en la cabeza.", a: true },
  { q: "Los grilliost ocultan sus orejas en sus patas delanteras.", a: true },
  { q: "Las garrapatas y ácaros son parientes de las arañas.", a: true },
  { q: "Las chinches y pulgas son insectos que no tienen alas.", a: true },
  { q: "Los escarabajos tienen alas delanteras duras que parecen un caparazón.", a: true },
  { q: "Las cucarachas pueden sobrevivir varios días sin cabeza.", a: true },
  { q: "Las mariposas monarca realizan migraciones larguísimas de miles de kilómetros.", a: true },
  { q: "Las termitas se alimentan principalmente de madera.", a: true },
  { q: "Las tijeretas son insectos peligrosos que cortan el cabello de la gente.", a: false },
  { q: "Los caracoles terrestres se mueven arrastrándose sobre un pie musculoso.", a: true },
  { q: "Las arañas tarántulas son las arañas más grandes del mundo.", a: true },
  { q: "Las pulgas pueden saltar más de 100 veces su propia altura.", a: true },
  { q: "Las mantis religiosas tienen sus patas delanteras dobladas como si rezaran.", a: true },
  { q: "Las libélulas son excelentes cazadoras voladoras de mosquitos.", a: true },
  { q: "Las hormigas se comunican entre sí utilizando sustancias químicas llamadas feromonas.", a: true },
  { q: "Las abejas reinas viven en la colmena y salen a cazar otros insectos.", a: false },
  { q: "Los escorpiones son arácnidos al igual que las arañas.", a: true },
  { q: "Los gusanos de seda fabrican capullos de hilo de seda natural.", a: true },
  { q: "Los abejorros son insectos polinizadores más grandes que las abejas de miel.", a: true },
  { q: "Las avispas mueren siempre tras picar una sola vez.", a: false },
  { q: "Las mariposas absorben el alimento líquido a través de una trompa enrollada llamada espiritrompa.", a: true },
  { q: "Las mariquitas rojas con puntos negros ayudan a proteger las plantas comiendo pulgones.", a: true },
  { q: "Las chinches de cama son pequeños insectos que se alimentan de plantas de jardín.", a: false },
  { q: "Las arañas viuda negra son conocidas por la marca de reloj de arena rojo en su abdomen.", a: true },
  { q: "Las chinchillas son insectos voladores de cuerpo verde.", a: false },
  { q: "Todos los insectos tienen esqueleto de huesos por dentro de su cuerpo.", a: false },
  { q: "Los insectos poseen un exoesqueleto duro por fuera que protege su cuerpo.", a: true }
];

const animalesLista = ["el perro", "el gato", "el león", "el elefante", "el tigre", "el caballo", "la vaca", "el conejo", "el águila", "el delfín", "el oso", "el zorro", "el lobo", "el mono", "la cebra"];
const rasgosLista = [
  { t: "tiene plumas para volar", trueFor: ["el águila"] },
  { t: "tiene 4 patas", trueFor: ["el perro", "el gato", "el león", "el elefante", "el tigre", "el caballo", "la vaca", "el conejo", "el oso", "el zorro", "el lobo", "el mono", "la cebra"] },
  { t: "nace de un huevo", trueFor: ["el águila"] },
  { t: "es un mamífero", trueFor: ["el perro", "el gato", "el león", "el elefante", "el tigre", "el caballo", "la vaca", "el conejo", "el delfín", "el oso", "el zorro", "el lobo", "el mono", "la cebra"] },
  { t: "vive en el mar", trueFor: ["el delfín"] }
];

for (let i = 0; i < 980; i++) {
  const anim = animalesLista[i % animalesLista.length];
  const tr = rasgosLista[Math.floor(Math.random() * rasgosLista.length)];
  const isTrue = tr.trueFor.includes(anim);
  preguntasAnimales.push({
    q: `¿Es cierto que ${anim} ${tr.t}?`,
    a: isTrue
  });
}
