var preguntasEspacio = [
  { q: "El Sol es una estrella muy brillante e inmensa.", a: true },
  { q: "La Tierra es el tercer planeta desde el Sol.", a: true },
  { q: "La Luna brilla porque produce su propia luz como un foco.", a: false },
  { q: "Los astronautas viajan al espacio en cohetes o naves espaciales.", a: true },
  { q: "El planeta Marte es conocido como el 'Planeta Rojo'.", a: true },
  { q: "Saturno es famoso por tener grandes anillos a su alrededor.", a: true },
  { q: "La fuerza de gravedad nos mantiene pegados al suelo.", a: true },
  { q: "En el espacio exterior hay aire para respirar normalmente.", a: false },
  { q: "El Sistema Solar tiene 8 planetas principales.", a: true },
  { q: "El Sol gira alrededor de la Tierra todos los días.", a: false },
  { q: "Un año en la Tierra tarda aproximadamente 365 días.", a: true },
  { q: "Júpiter es el planeta más grande de nuestro Sistema Solar.", a: true },
  { q: "Las estrellas se apagan completamente todas las mañanas.", a: false },
  { q: "Los cometas están hechos de hielo, polvo y rocas.", a: true },
  { q: "Los trajes espaciales protegen a los astronautas del frío extremo.", a: true },
  { q: "La Luna gira alrededor de nuestro planeta Tierra.", a: true },
  { q: "Un eclipse solar ocurre cuando la Luna se interpone entre el Sol y la Tierra.", a: true },
  { q: "El telescopio es un instrumento que sirve para mirar las estrellas lejanas.", a: true },
  { q: "Neptuno es un planeta muy helado y lejano al Sol.", a: true },
  { q: "En la Luna hay mucha gravedad y por eso es difícil saltar.", a: false },
  { q: "La Vía Láctea es la galaxia donde se encuentra nuestro Sistema Solar.", a: true },
  { q: "Mercurio es el planeta más cercano al Sol.", a: true },
  { q: "Venus es el planeta más caliente del Sistema Solar.", a: true },
  { q: "La Tierra tiene un satélite natural llamado Luna.", a: true },
  { q: "Los astronautas pueden flotar en el espacio porque no hay gravedad.", a: true },
  { q: "El Sol es una estrella pequeña comparada con otras estrellas.", a: true },
  { q: "Los planetas se mueven alrededor del Sol en órbitas circulares.", a: true },
  { q: "La Luna está más cerca de la Tierra que el Sol.", a: true },
  { q: "En el espacio hay muchas estrellas, planetas y galaxias.", a: true },
  { q: "Un cohete necesita combustible para despegar hacia el espacio.", a: true },
  { q: "Plutón ya no es considerado un planeta principal.", a: true },
  { q: "Los agujeros negros son regiones del espacio con mucha gravedad.", a: true },
  { q: "La Tierra tiene forma de esfera achatada por los polos.", a: true },
  { q: "Un día en la Tierra dura 24 horas porque gira sobre sí misma.", a: true },
  { q: "El Sol nos da luz y calor para que haya vida en la Tierra.", a: true },
  { q: "Las estrellas fugaces son meteoritos que arden al entrar a la atmósfera.", a: true },
  { q: "La Estación Espacial Internacional orbita alrededor de la Tierra.", a: true },
  { q: "Los planetas rocosos son Mercurio, Venus, Tierra y Marte.", a: true },
  { q: "Los planetas gaseosos son Júpiter, Saturno, Urano y Neptuno.", a: true },
  { q: "La temperatura en el espacio puede ser muy fría y muy caliente.", a: true },
  { q: "Los astronautas comen alimentos especiales en el espacio.", a: true },
  { q: "El cohete Saturno V llevó al hombre a la Luna.", a: true },
  { q: "Neil Armstrong fue el primer hombre en pisar la Luna.", a: true },
  { q: "La huella de Neil Armstrong en la Luna aún está allí.", a: true },
  { q: "En la Luna no hay viento ni lluvia.", a: true },
  { q: "Los astronautas entrenan mucho antes de viajar al espacio.", a: true },
  { q: "El espacio exterior es completamente silencioso.", a: true },
  { q: "En el espacio no se puede oír sonidos porque no hay aire.", a: true },
  { q: "Las naves espaciales tienen paneles solares para obtener energía.", a: true },
  { q: "El cinturón de asteroides está entre Marte y Júpiter.", a: true },
  { q: "Los asteroides son rocas que orbitan alrededor del Sol.", a: true },
  { q: "Un meteoro es un asteroide que entra en la atmósfera terrestre.", a: true },
  { q: "Un cráter es un agujero en la superficie de un planeta o luna.", a: true },
  { q: "La Tierra tiene una atmósfera que nos protege de los rayos del Sol.", a: true },
  { q: "El oxígeno de la Tierra proviene de las plantas y el agua.", a: true },
  { q: "Los planetas no tienen luz propia, reflejan la luz del Sol.", a: true },
  { q: "La Luna tarda aproximadamente 28 días en dar la vuelta a la Tierra.", a: true },
  { q: "La Tierra está inclinada y por eso tenemos estaciones del año.", a: true },
  { q: "El ecuador es la línea imaginaria que divide la Tierra en dos mitades.", a: true },
  { q: "Los polos norte y sur son las zonas más frías de la Tierra.", a: true },
  { q: "Un satélite artificial es un objeto creado por humanos que orbita la Tierra.", a: true },
  { q: "El GPS funciona gracias a satélites en el espacio.", a: true },
  { q: "Los telescopios espaciales nos muestran imágenes increíbles del universo.", a: true },
  { q: "El telescopio Hubble ha tomado fotos del espacio profundo.", a: true },
  { q: "Las galaxias están formadas por millones de estrellas.", a: true },
  { q: "La galaxia Andrómeda es vecina de la Vía Láctea.", a: true },
  { q: "El espacio es muy grande y está en constante expansión.", a: true },
  { q: "Los astronautas duermen en bolsas de dormir pegadas a la pared.", a: true },
  { q: "En el espacio no hay día ni noche como en la Tierra.", a: true },
  { q: "La luz del Sol tarda 8 minutos en llegar a la Tierra.", a: true },
  { q: "Algunas estrellas son más grandes que el Sol.", a: true },
  { q: "Las estrellas nacen y mueren después de millones de años.", a: true },
  { q: "Una supernova es la explosión de una estrella al morir.", a: true },
  { q: "Las constelaciones son grupos de estrellas que forman figuras.", a: true },
  { q: "El carro es una constelación muy conocida en el hemisferio norte.", a: true },
  { q: "La estrella Polar siempre indica el norte.", a: true },
  { q: "Los planetas pueden tener lunas orbitando a su alrededor.", a: true },
  { q: "Júpiter tiene muchas lunas, la más grande es Ganímedes.", a: true },
  { q: "Saturno tiene lunas también, Titán es una de ellas.", a: true },
  { q: "En Titán hay lagos de metano líquido.", a: true },
  { q: "Marte tiene el volcán más grande del Sistema Solar: el Monte Olimpo.", a: true },
  { q: "El Monte Olimpo en Marte es más alto que el Everest.", a: true },
  { q: "Venus es el planeta más brillante en el cielo nocturno.", a: true },
  { q: "Venus gira al revés comparado con otros planetas.", a: true },
  { q: "Un día en Venus dura más que un año en Venus.", a: true },
  { q: "Mercurio tiene cráteres como la Luna.", a: true },
  { q: "Mercurio no tiene atmósfera y por eso hace mucho calor y frío.", a: true },
  { q: "Neptuno es el planeta más ventoso del Sistema Solar.", a: true },
  { q: "Urano gira de lado, como si estuviera recostado.", a: true },
  { q: "Los anillos de Saturno están hechos de hielo y rocas.", a: true },
  { q: "Los anillos de Saturno se pueden ver con un telescopio.", a: true },
  { q: "El Sol es la fuente de energía principal para la Tierra.", a: true },
  { q: "La gravedad del Sol mantiene a los planetas en órbita.", a: true },
  { q: "Las mareas en la Tierra son causadas por la gravedad de la Luna.", a: true },
  { q: "El día y la noche ocurren porque la Tierra gira.", a: true },
  { q: "El año bisiesto tiene 366 días y ocurre cada 4 años.", a: true },
  { q: "El equinoccio ocurre cuando el día y la noche duran igual.", a: true },
  { q: "El solsticio de verano es el día más largo del año.", a: true },
  { q: "La luz del Sol es blanca pero se separa en colores con un prisma.", a: true },
  { q: "El color de una estrella indica su temperatura.", a: true },
  { q: "Las estrellas azules son más calientes que las rojas.", a: true },
  { q: "Las estrellas rojas son más frías que las azules.", a: true },
  { q: "El Big Bang fue una gran explosión que dio origen al universo.", a: true },
  { q: "El universo tiene más de 13 mil millones de años.", a: true },
  { q: "Los astronautas hacen ejercicio en el espacio para mantener sus músculos.", a: true },
  { q: "En el espacio los huesos se debilitan si no se hace ejercicio.", a: true },
  { q: "La comida en el espacio viene en paquetes sellados.", a: true },
  { q: "Los astronautas beben agua de bolsas con sorbetes.", a: true },
  { q: "En el espacio no se puede usar una taza normal para beber.", a: true },
  { q: "Los cohetes se lanzan desde plataformas especiales.", a: true },
  { q: "El centro de control de misiones vigila los viajes espaciales.", a: true },
  { q: "La NASA es la agencia espacial de Estados Unidos.", a: true },
  { q: "La Agencia Espacial Europea también envía cohetes al espacio.", a: true },
  { q: "Rusia tiene su propia agencia espacial llamada Roscosmos.", a: true },
  { q: "China tiene una agencia espacial que ha llevado astronautas al espacio.", a: true },
  { q: "Los primeros animales en ir al espacio fueron perros y monos.", a: true },
  { q: "La perra Laika fue el primer animal en orbitar la Tierra.", a: true },
  { q: "El primer ser humano en ir al espacio fue Yuri Gagarin.", a: true },
  { q: "Yuri Gagarin viajó en la nave Vostok 1.", a: true },
  { q: "Alan Shepard fue el primer estadounidense en el espacio.", a: true },
  { q: "John Glenn fue el primer estadounidense en orbitar la Tierra.", a: true },
  { q: "El Apolo 11 fue la misión que llevó al hombre a la Luna.", a: true },
  { q: "Buzz Aldrin fue el segundo hombre en pisar la Luna.", a: true },
  { q: "Michael Collins orbitó la Luna mientras Armstrong y Aldrin caminaban.", a: true },
  { q: "La misión Apolo 13 tuvo problemas pero los astronautas regresaron a salvo.", a: true },
  { q: "El transbordador espacial fue un vehículo reutilizable.", a: true },
  { q: "El transbordador espacial Columbia fue el primero en volar.", a: true },
  { q: "El telescopio espacial James Webb es más nuevo y potente que el Hubble.", a: true },
  { q: "El James Webb puede ver el universo infrarrojo.", a: true },
  { q: "La Estación Espacial Internacional tiene el tamaño de un campo de fútbol.", a: true },
  { q: "La ISS orbita la Tierra a unos 400 kilómetros de altura.", a: true },
  { q: "Los astronautas pueden ver 16 amaneceres por día en la ISS.", a: true },
  { q: "La basura espacial son objetos hechos por humanos que orbitan la Tierra.", a: true },
  { q: "Los satélites meteorológicos nos ayudan a predecir el clima.", a: true },
  { q: "Los satélites de comunicación permiten ver televisión y usar teléfonos.", a: true },
  { q: "El planeta enano Ceres está en el cinturón de asteroides.", a: true },
  { q: "Plutón tiene cinco lunas conocidas.", a: true },
  { q: "La luna más grande de Plutón se llama Caronte.", a: true },
  { q: "El cinturón de Kuiper está más allá de Neptuno.", a: true },
  { q: "La nube de Oort está en el límite del Sistema Solar.", a: true },
  { q: "Los cometas vienen de la nube de Oort y el cinturón de Kuiper.", a: true },
  { q: "El cometa Halley pasa cerca de la Tierra cada 76 años.", a: true },
  { q: "La lluvia de estrellas ocurre cuando la Tierra pasa por restos de cometas.", a: true },
  { q: "Las Perseidas son una lluvia de estrellas famosa en agosto.", a: true },
  { q: "La luz de la Luna es luz del Sol reflejada.", a: true },
  { q: "La Luna tiene fases: nueva, creciente, llena y menguante.", a: true },
  { q: "Eclipse lunar ocurre cuando la Tierra se interpone entre el Sol y la Luna.", a: true },
  { q: "En un eclipse lunar, la Luna se ve rojiza.", a: true },
  { q: "Los telescopios terrestres están en montañas altas.", a: true },
  { q: "El observatorio de Mauna Kea está en Hawái.", a: true },
  { q: "El radiotelescopio de Arecibo era muy grande y famoso.", a: true },
  { q: "Los radiotelescopios captan ondas de radio del espacio.", a: true },
  { q: "La velocidad de la luz es de 300,000 kilómetros por segundo.", a: true },
  { q: "Un año luz es la distancia que recorre la luz en un año.", a: true },
  { q: "La estrella más cercana al Sol es Próxima Centauri.", a: true },
  { q: "Próxima Centauri está a 4.2 años luz de distancia.", a: true },
  { q: "La Tierra es el único planeta conocido con vida.", a: true },
  { q: "Los exoplanetas son planetas que orbitan otras estrellas.", a: true },
  { q: "El telescopio Kepler ha descubierto muchos exoplanetas.", a: true },
  { q: "Algunos exoplanetas están en la zona habitable de su estrella.", a: true },
  { q: "La zona habitable es donde puede haber agua líquida.", a: true },
  { q: "El agua es esencial para la vida como la conocemos.", a: true },
  { q: "En Marte hay hielo de agua en los polos.", a: true },
  { q: "Los rovers exploran Marte para buscar señales de vida.", a: true },
  { q: "Curiosity es un rover que explora Marte.", a: true },
  { q: "Perseverance es otro rover que busca vida en Marte.", a: true },
  { q: "El helicóptero Ingenuity voló en Marte.", a: true },
  { q: "La sonda Voyager 1 está en el espacio interestelar.", a: true },
  { q: "La Voyager 1 lleva un mensaje para posibles extraterrestres.", a: true },
  { q: "Las sondas espaciales exploran planetas sin astronautas.", a: true },
  { q: "La sonda Cassini exploró Saturno y sus anillos.", a: true },
  { q: "La sonda Juno está explorando Júpiter.", a: true },
  { q: "La sonda Parker estudia el Sol desde muy cerca.", a: true },
  { q: "El sol tiene manchas solares que son regiones más frías.", a: true },
  { q: "Las erupciones solares pueden afectar las comunicaciones en la Tierra.", a: true },
  { q: "La aurora boreal es causada por partículas del Sol.", a: true },
  { q: "La aurora boreal se ve en los polos norte y sur.", a: true },
  { q: "El magnetismo de la Tierra nos protege del viento solar.", a: true },
  { q: "La atmósfera terrestre tiene varias capas.", a: true },
  { q: "La capa de ozono nos protege de los rayos UV.", a: true },
  { q: "La ionosfera refleja las ondas de radio.", a: true },
  { q: "La troposfera es donde ocurre el clima.", a: true },
  { q: "La estratosfera es donde vuelan los aviones.", a: true },
  { q: "La mesosfera es donde se queman los meteoritos.", a: true },
  { q: "La termosfera es muy caliente y donde está la ISS.", a: true },
  { q: "La exosfera es la capa más externa de la atmósfera.", a: true },
  { q: "El color azul del cielo es por la dispersión de la luz solar.", a: true },
  { q: "El atardecer es rojo porque la luz viaja más distancia en la atmósfera.", a: true },
  { q: "El arcoíris se forma cuando la luz del Sol se refracta en las gotas de agua.", a: true },
  { q: "Las nubes están hechas de pequeñas gotas de agua.", a: true },
  { q: "La lluvia ocurre cuando las gotas de agua en las nubes se vuelven pesadas.", a: true },
  { q: "La nieve se forma cuando el vapor de agua se congela.", a: true },
  { q: "El granizo son bolas de hielo que caen de las nubes.", a: true },
  { q: "Los tornados son columnas de aire que giran violentamente.", a: true },
  { q: "Los huracanes son tormentas gigantes que se forman en el mar.", a: true },
  { q: "El cambio climático está afectando el clima en todo el mundo.", a: true },
  { q: "El planeta Tierra es muy especial por tener vida y agua líquida.", a: true },
  { q: "Debemos cuidar nuestro planeta para que siga siendo habitable.", a: true }
];

const planetasLista = ["Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno"];

for (let i = 0; i < 980; i++) {
  const p = planetasLista[i % planetasLista.length];
  const isTrue = Math.random() > 0.5;
  const qText = isTrue 
    ? `¿${p} forma parte de los planetas del Sistema Solar?` 
    : `¿Es cierto que ${p} es una luna que gira alrededor de la Tierra?`;
  preguntasEspacio.push({
    q: qText,
    a: isTrue
  });
}
