const preguntasCuerpo = [
  { "q": "El corazón bombea sangre a todo nuestro cuerpo.", "a": true },
  { "q": "Los pulmones nos sirven para digerir los alimentos.", "a": false },
  { "q": "El estómago ayuda a procesar la comida que ingerimos.", "a": true },
  { "q": "El cerebro está protegido dentro del cráneo.", "a": true },
  { "q": "La piel es el órgano más grande de nuestro cuerpo.", "a": true },
  { "q": "Respiramos oxígeno y expulsamos dióxido de carbono.", "a": true },
  { "q": "La sangre transporta nutrientes y oxígeno a todo el cuerpo.", "a": true },
  { "q": "El cerebro envía señales a los músculos para que podamos movernos.", "a": true },
  { "q": "El intestino delgado absorbe los nutrientes de los alimentos.", "a": true },
  { "q": "El estómago produce jugos gástricos para deshacer la comida.", "a": true },
  { "q": "Los pulmones se llenan de agua cuando respiramos profundo.", "a": false },
  { "q": "El corazón late más rápido cuando corremos o hacemos ejercicio.", "a": true },
  { "q": "Los riñones ayudan a limpiar y filtrar la sangre.", "a": true },
  { "q": "El hígado es un órgano que ayuda en la digestión de los alimentos.", "a": true },
  { "q": "El cerebro nunca descansa, incluso cuando estamos dormidos.", "a": true },
  { "q": "El aire entra a nuestro cuerpo por la nariz o la boca.", "a": true },
  { "q": "El esófago es el tubo que lleva la comida desde la boca hasta el estómago.", "a": true },
  { "q": "El corazón se encuentra en el lado derecho de la cabeza.", "a": false },
  { "q": "Los pulmones se encuentran dentro del tórax o pecho.", "a": true },
  { "q": "El estómago se encarga de fabricar los pensamientos y recuerdos.", "a": false },
  { "q": "Las venas y las arterias son como tubitos por donde viaja la sangre.", "a": true },
  { "q": "La sangre es de color azul cuando circula dentro del cuerpo humano.", "a": false },
  { "q": "El pulso indica las veces que el corazón late en un minuto.", "a": true },
  { "q": "Las costillas forman una caja de huesos para proteger el corazón y pulmones.", "a": true },
  { "q": "El intestino grueso elimina lo que el cuerpo no necesita en forma de excremento.", "a": true },
  { "q": "La vejiga almacena la orina antes de ir al baño.", "a": true },
  { "q": "El cerebro controla el parpadeo de los ojos de forma automática.", "a": true },
  { "q": "Los pulmones son dos órganos blandos y esponjosos.", "a": true },
  { "q": "El corazón de un niño late más despacio que el de un adulto en reposo.", "a": false },
  { "q": "Masticar bien la comida ayuda a que el estómago haga mejor su trabajo.", "a": true },
  { "q": "La saliva ayuda a humedecer y ablandar los alimentos en la boca.", "a": true },
  { "q": "El hipo ocurre por un movimiento repentino del diafragma.", "a": true },
  { "q": "Los riñones producen la saliva que tenemos en la boca.", "a": false },
  { "q": "El cerebro nos permite sentir emociones como alegría, tristeza o miedo.", "a": true },
  { "q": "Los estornudos expulsan aire rápidamente para limpiar la nariz.", "a": true },
  { "q": "La tos ayuda a limpiar las vías respiratorias cuando hay polvo o mucosidad.", "a": true },
  { "q": "El sudor nos ayuda a enfriar el cuerpo cuando tenemos calor.", "a": true },
  { "q": "Los latidos del corazón se detienen por completo mientras dormimos.", "a": false },
  { "q": "El cráneo es el hueso duro que cubre y protege el cerebro.", "a": true },
  { "q": "Los humanos tenemos 5 sentidos.", "a": true },
  { "q": "El sentido del gusto está en la boca y la lengua.", "a": true },
  { "q": "Los ojos nos permiten escuchar sonidos fuertes.", "a": false },
  { "q": "Las pestañas ayudan a proteger los ojos del polvo.", "a": true },
  { "q": "El oído interno nos ayuda a mantener el equilibrio.", "a": true },
  { "q": "Las papilas gustativas de la lengua detectan sabores como dulce, salado y ácido.", "a": true },
  { "q": "El sentido del tacto está únicamente en las palmas de las manos.", "a": false },
  { "q": "Las cejas evitan que el sudor de la frente caiga dentro de los ojos.", "a": true },
  { "q": "Las orejas atrapan las ondas de sonido para enviarlas al interior del oído.", "a": true },
  { "q": "El sentido del olfato nos permite distinguir los olores con la nariz.", "a": true },
  { "q": "La pupila es la parte negra en el centro del ojo que cambia de tamaño según la luz.", "a": true },
  { "q": "Si hay mucha luz, la pupila del ojo se hace más grande.", "a": false },
  { "q": "El tímpano es una fina membrana dentro del oído que vibra con los sonidos.", "a": true },
  { "q": "Los parpados se cierran automáticamente para proteger los ojos.", "a": true },
  { "q": "La piel puede sentir el calor, el frío, el dolor y las texturas suaves o rugosas.", "a": true },
  { "q": "El sentido del gusto y el olfato trabajan juntos cuando comemos.", "a": true },
  { "q": "Los ciegos pueden leer usando un sistema de puntos en relieve llamado Braille.", "a": true },
  { "q": "Las personas sorda usan el lenguaje de señas con las manos para comunicarse.", "a": true },
  { "q": "Podemos sentir el dolor porque los nervios envían señales de alerta al cerebro.", "a": true },
  { "q": "La cera del oído sirve para atrapar la suciedad y proteger el canal auditivo.", "a": true },
  { "q": "Ver la televisión muy de cerca ayuda a mejorar la vista.", "a": false },
  { "q": "Usar gafas de sol ayuda a proteger los ojos de los rayos ultravioleta.", "a": true },
  { "q": "Las lágrimas sirven para mantener limpios y húmedos los ojos.", "a": true },
  { "q": "El sentido de la vista funciona gracias a los ojos y al cerebro.", "a": true },
  { "q": "Escuchar música con auriculares a volumen muy alto puede dañar la audición.", "a": true },
  { "q": "La lengua es un músculo muy flexible.", "a": true },
  { "q": "Los perros tienen el sentido del olfato mucho más desarrollado que los humanos.", "a": true },
  { "q": "La punta de los dedos de las manos no tiene sensibilidad al tacto.", "a": false },
  { "q": "Podemos oler la comida antes de probarla gracias a los receptores de la nariz.", "a": true },
  { "q": "Los ojos pueden ver en completa oscuridad sin ninguna luz.", "a": false },
  { "q": "El esqueleto sostiene nuestro cuerpo y protege los órganos.", "a": true },
  { "q": "El esqueleto de un adulto tiene más de 200 huesos.", "a": true },
  { "q": "Los músculos nos permiten movernos y correr.", "a": true },
  { "q": "Los huesos son estructuras duras y resistentes.", "a": true },
  { "q": "Las articulaciones son los lugares donde se unen dos o más huesos.", "a": true },
  { "q": "Los rodillas y los codos son ejemplos de articulaciones.", "a": true },
  { "q": "Los músculos se estiran y se contraen para mover los huesos.", "a": true },
  { "q": "El fémur es el hueso más largo del cuerpo humano y está en la pierna.", "a": true },
  { "q": "Los huesos son elementos completamente muertos que no crecen.", "a": false },
  { "q": "El calcio que obtenemos de alimentos como la leche ayuda a fortalecer los huesos.", "a": true },
  { "q": "La columna vertebral nos permite mantenernos de pie y doblar la espalda.", "a": true },
  { "q": "Tenemos músculos en la cara que nos permiten sonreír y hacer gestos.", "a": true },
  { "q": "Los huesos de los niños son exactamente del mismo tamaño que los de un adulto.", "a": false },
  { "q": "Si un hueso se rompe, el cuerpo tiene la capacidad de regenerarlo y soldarlo.", "a": true },
  { "q": "Las vértebras son los pequeños huesos que forman la columna vertebral.", "a": true },
  { "q": "Los tendones unen los músculos a los huesos.", "a": true },
  { "q": "El cuerpo humano tiene más de 600 músculos en total.", "a": true },
  { "q": "El estribo es el hueso más pequeño del cuerpo humano y está en el oído.", "a": true },
  { "q": "La mandíbula es el único hueso móvil de la cabeza que nos permite masticar.", "a": true },
  { "q": "Sin huesos ni músculos, nuestro cuerpo se caería como una gelatina.", "a": true },
  { "q": "Hacer ejercicio físico ayuda a fortalecer tanto los músculos como los huesos.", "a": true },
  { "q": "El hueso de la risa es un hueso gigante ubicado en el estómago.", "a": false },
  { "q": "El cuello nos permite girar y mover la cabeza en distintas direcciones.", "a": true },
  { "q": "La cadera conecta el tronco de nuestro cuerpo con las piernas.", "a": true },
  { "q": "Los dedos de los pies no tienen ningún hueso por dentro.", "a": false },
  { "q": "El cartílago es un tejido más blando y flexible que el hueso, como en la punta de la nariz.", "a": true },
  { "q": "Las orejas están formadas por hueso duro que no se puede doblar.", "a": false },
  { "q": "Los nudillos son las articulaciones de los dedos de la mano.", "a": true },
  { "q": "Sentarse con la espalda recta ayuda a cuidar la columna vertebral.", "a": true },
  { "q": "Los músculos se debilitan si nunca hacemos actividad física.", "a": true },
  { "q": "Los dientes de leche duran para toda la vida.", "a": false },
  { "q": "Lavarnos las manos ayuda a eliminar gérmenes y bacterias.", "a": true },
  { "q": "Beber agua es muy importante para mantenernos sanos.", "a": true },
  { "q": "Las uñas crecen en los dedos de las manos y pies.", "a": true },
  { "q": "Dormir bien ayuda a que nuestro cuerpo recupere energía.", "a": true },
  { "q": "Cepillarse los dientes después de comer evita la formación de caries.", "a": true },
  { "q": "Comer frutas y verduras nos aporta vitaminas indispensables para la salud.", "a": true },
  { "q": "Bañarse seguido limpia la piel y evita malos olores e infecciones.", "a": true },
  { "q": "Vacunarse ayuda a nuestro sistema inmunitario a protegerse contra enfermedades.", "a": true },
  { "q": "Los dientes definitivos salen después de que se caen los dientes de leche.", "a": true },
  { "q": "Los molares o muelas sirven para triturar los alimentos.", "a": true },
  { "q": "Los gérmenes son tan grandes que podemos verlos fácilmente a simple vista.", "a": false },
  { "q": "Cubrirse la boca con el antebrazo al toser evita contagiar a otras personas.", "a": true },
  { "q": "Lavarse las manos antes de comer es una buena costumbre de higiene.", "a": true },
  { "q": "Comer dulces y golosinas todo el día es excelente para la salud de los dientes.", "a": false },
  { "q": "La fiebre es una señal de que el cuerpo está luchando contra una infección.", "a": true },
  { "q": "Cortarse las uñas de las manos previene que se acumule suciedad debajo de ellas.", "a": true },
  { "q": "Usar protector solar cuida la piel de las quemaduras del sol.", "a": true },
  { "q": "El descanso nocturno de 8 a 10 horas es necesario para que los niños crezcan sanos.", "a": true },
  { "q": "El hilo dental ayuda a limpiar la suciedad que queda entre los dientes.", "a": true },
  { "q": "Beber refrescos con mucho azúcar reemplaza completamente al agua natural.", "a": false },
  { "q": "El médico especialista en cuidar los dientes se llama dentista u odontólogo.", "a": true },
  { "q": "Lavar las frutas antes de comerlas elimina restos de tierra y bacterias.", "a": true },
  { "q": "El sistema inmunitario es la defensa natural del cuerpo contra las enfermedades.", "a": true },
  { "q": "Compartir el cepillo de dientes con un amigo es muy higiénico.", "a": false },
  { "q": "Las costras se forman sobre las heridas para proteger la piel mientras sana.", "a": true },
  { "q": "Caminar o andar en bicicleta son formas divertidas de ejercitar el cuerpo.", "a": true },
  { "q": "Un botiquín de primeros auxilios contiene elementos para curar pequeñas heridas.", "a": true },
  { "q": "El lavado de manos debe durar al menos 20 segundos con agua y jabón.", "a": true },
  { "q": "La falta de sueño puede hacer que nos sintamos cansados y de mal humor.", "a": true },
  { "q": "El cabello y las uñas están hechos de una proteína llamada queratina.", "a": true },
  { "q": "Las huellas dactilares de los dedos son únicas para cada persona en el mundo.", "a": true },
  { "q": "Incluso los gemelos idénticos tienen huellas dactilares diferentes.", "a": true },
  { "q": "Los bebés nacen con más huesos que un adulto, pero luego algunos se unen.", "a": true },
  { "q": "El color de los ojos depende de la cantidad de melanina que tengamos.", "a": true },
  { "q": "El cabello deja de crecer por completo cuando nos quedamos dormidos.", "a": false },
  { "q": "El ombligo es la cicatriz que nos queda al nacer cuando se corta el cordón umbilical.", "a": true },
  { "q": "Rascarnos la piel cuando nos pica un mosquito elimina el veneno por completo.", "a": false },
  { "q": "A todas las personas les crecen las uñas de la mano dominante un poco más rápido.", "a": true },
  { "q": "Los escalofríos son temblores involuntarios del cuerpo para generar calor.", "a": true },
  { "q": "Las mariposas en el estómago son una sensación real causada por los nervios.", "a": true },
  { "q": "El tono de la voz cambia a medida que los niños van creciendo.", "a": true },
  { "q": "Los seres humanos pierden miles de células muertas de la piel cada día.", "a": true },
  { "q": "El estornudo puede viajar a gran velocidad por el aire.", "a": true },
  { "q": "Los bostezos a veces se contagian cuando vemos a otra persona bostezar.", "a": true },
  { "q": "Las personas tenemos exactamente el mismo número de cabellos en la cabeza.", "a": false },
  { "q": "El cuerpo de un ser humano está compuesto en su mayoría por agua.", "a": true },
  { "q": "Los humanos podemos vivir meses sin comer y sin beber agua.", "a": false },
  { "q": "La digestión completa de una comida tarda varias horas dentro del cuerpo.", "a": true },
  { "q": "Crecer significa que nuestros huesos y músculos se van haciendo más grandes y fuertes.", "a": true },
  { "q": "El cerebro de los niños aprende cosas nuevas a gran velocidad cada día.", "a": true },
  { "q": "La lengua tiene músculos que nos permiten tragar la comida.", "a": true },
  { "q": "Los párpados ayudan a limpiar el ojo cada vez que parpadeamos.", "a": true },
  { "q": "El sentido del oído se encarga de procesar los colores que vemos.", "a": false },
  { "q": "Los dientes caninos o colmillos sirven para desgarrar algunos alimentos.", "a": true },
  { "q": "El sudor no tiene olor al principio, el olor lo causan las bacterias de la piel.", "a": true },
  { "q": "Los glóbulos rojos de la sangre son los encargados de llevar oxígeno.", "a": true },
  { "q": "Los glóbulos blancos de la sangre ayudan a combatir las infecciones y gérmenes.", "a": true },
  { "q": "Las plaquetas ayudan a tapar las heridas y detener el sangrado.", "a": true },
  { "q": "La tráquea es el tubo por donde pasa el aire hacia los pulmones.", "a": true },
  { "q": "El páncreas es un órgano que ayuda a controlar el azúcar en la sangre.", "a": true },
  { "q": "Los seres humanos tenemos dos pulmones de exactamente el mismo tamaño.", "a": false },
  { "q": "El corazón está ubicado en el pecho, ligeramente inclinado hacia la izquierda.", "a": true },
  { "q": "La epidermis es la capa más externa de la piel.", "a": true },
  { "q": "Los bellos de la nariz ayudan a filtrar el polvo del aire que respiramos.", "a": true },
  { "q": "Podemos tragar comida y respirar aire al mismo tiempo sin ahogarnos.", "a": false },
  { "q": "La epiglotis es una pequeña tapa que evita que la comida se vaya a los pulmones.", "a": true },
  { "q": "El cuerpo humano produce más saliva cuando ve o huele comida deliciosa.", "a": true },
  { "q": "Las cejas están hechas de músculo sólido sin nada de pelo.", "a": false },
  { "q": "Los huesos contienen médula ósea en su interior, donde se fabrica la sangre.", "a": true },
  { "q": "El intestino delgado es más largo que el intestino grueso.", "a": true },
  { "q": "El intestino delgado puede medir varios metros de largo bien enrollado.", "a": true },
  { "q": "Los pulmones expulsan agua cuando respiramos en un día frío y se ve vapor.", "a": true },
  { "q": "La frecuencia cardíaca es más baja cuando estamos descansando tranquilos.", "a": true },
  { "q": "Los calambres musculares ocurren a veces por falta de agua o minerales.", "a": true },
  { "q": "La piel nos protege contra la entrada de gérmenes al interior del cuerpo.", "a": true },
  { "q": "Las quemaduras de sol dañan la capa protectora de la piel.", "a": true },
  { "q": "El oxígeno entra en la sangre a través de los alvéolos en los pulmones.", "a": true },
  { "q": "Las arterias llevan sangre con oxígeno desde el corazón al resto del cuerpo.", "a": true },
  { "q": "Las venas devuelven la sangre al corazón para que vuelva a cargarse de oxígeno.", "a": true },
  { "q": "Las personas tienen diferentes tipos de sangre como A, B, AB y O.", "a": true },
  { "q": "La temperatura normal del cuerpo humano es de unos 36 a 37 grados centígrados.", "a": true },
  { "q": "Tener una temperatura corporal de 40 grados significa que tenemos fiebre alta.", "a": true },
  { "q": "El esternón es el hueso plano situado en el centro del pecho.", "a": true },
  { "q": "Las costillas flotantes no están unidas al esternón por delante.", "a": true },
  { "q": "El cráneo está formado por varios huesos encajados como un rompecabezas.", "a": true },
  { "q": "La pelvis sostiene los órganos del abdomen y se conecta con las piernas.", "a": true },
  { "q": "El calcáneo es el hueso que forma el talón del pie.", "a": true },
  { "q": "El bíceps y el tríceps son músculos que están en el brazo.", "a": true },
  { "q": "Los músculos gemelos o pantorrillas están ubicados en la parte trasera de la pierna.", "a": true },
  { "q": "Los abdominales son músculos que protegen la zona del vientre.", "a": true },
  { "q": "El diafragma es el músculo principal que nos ayuda a inspirar y espirar aire.", "a": true },
  { "q": "Respirar aire limpio de la naturaleza es sano para nuestros pulmones.", "a": true },
  { "q": "El humo del tabaco y la contaminación dañan los pulmones.", "a": true },
  { "q": "Morderse las uñas puede llevar bacterias de las manos a la boca.", "a": true },
  { "q": "Lavarse los oídos introduciendo objetos punzantes es muy seguro.", "a": false },
  { "q": "El sudor nos ayuda a eliminar algunas toxinas del cuerpo.", "a": true },
  { "q": "El esmalte dental es la sustancia más dura de todo el cuerpo humano.", "a": true },
  { "q": "El hipotálamo en el cerebro funciona como el termómetro del cuerpo.", "a": true },
  { "q": "Los temblores en las manos al hacer fuerza se deben a la fatiga muscular.", "a": true },
  { "q": "Dormir a oscuras ayuda al cerebro a producir melatonina para descansar mejor.", "a": true }
];

const sentidosLista = [
  { sense: "la vista", organ: "los ojos", falseOrgan: "las orejas" },
  { sense: "el oído", organ: "las orejas", falseOrgan: "la nariz" },
  { sense: "el olfato", organ: "la nariz", falseOrgan: "los ojos" },
  { sense: "el gusto", organ: "la lengua", falseOrgan: "los pies" },
  { sense: "el tacto", organ: "la piel", falseOrgan: "los dientes" }
];

for (let i = 0; i < 980; i++) {
  const s = sentidosLista[i % sentidosLista.length];
  const isTrue = Math.random() > 0.5;
  const organUsed = isTrue ? s.organ : s.falseOrgan;
  preguntasCuerpo.push({
    q: `¿El sentido de ${s.sense} funciona principalmente a través de ${organUsed}?`,
    a: isTrue
  });
}
