const preguntasMatematicas = [
  { q: "Un triángulo tiene 3 lados.", a: true },
  { q: "Un cuadrado tiene 5 lados.", a: false },
  { q: "Un rectángulo tiene 4 lados.", a: true },
  { q: "Un círculo tiene esquinas puntudas.", a: false },
  { q: "Un pentágono tiene 5 lados.", a: true },
  { q: "Un hexágono tiene 6 lados.", a: true },
  { q: "Un cubo tiene forma de caja tridimensional.", a: true },
  { q: "Una esfera rueda fácilmente porque es redonda.", a: true },
  { q: "Un triángulo tiene 4 vértices (esquinas).", a: false },
  { q: "Un cuadrado tiene todos sus lados de la misma medida.", a: true },
  { q: "Un rectángulo tiene 3 lados.", a: false },
  { q: "Un circulo no tiene lados rectos.", a: true },
  { q: "Un cilindro parece un tubo o lata de refresco.", a: true },
  { q: "Un cubo tiene 6 caras cuadradas.", a: true },
  { q: "Un óvalo es completamente cuadrado.", a: false },
  { q: "Un pirámide termina en una punta arriba.", a: true },
  { q: "Las ruedas de las bicicletas tienen forma de cuadrado.", a: false },
  { q: "Un dado común de juego tiene forma de cubo.", a: true },
  { q: "Un triángulo tiene más lados que un cuadrado.", a: false },
  { q: "Un pentágono tiene más lados que un triángulo.", a: true },
  { q: "Un hexágono tiene menos lados que un triángulo.", a: false },
  { q: "Un cuadrado tiene 4 esquinas o vértices.", a: true },
  { q: "Un rectángulo tiene 2 lados más largos y 2 lados más cortos.", a: true },
  { q: "Una pelota de fútbol tiene forma de esfera.", a: true },
  { q: "Un triángulo tiene 3 esquinas.", a: true },
  { q: "Una caja de zapatos suele tener forma de prisma rectangular.", a: true },
  { q: "Un anillo tiene forma circular.", a: true },
  { q: "Un triángulo de cuatro lados se llama cuadrilátero.", a: false },
  { q: "Un rombo tiene 4 lados.", a: true },
  { q: "Un cono de helado se parece a la figura geométrica llamada cono.", a: true },
  { q: "Una moneda tiene forma redonda.", a: true },
  { q: "Un espejo cuadrado tiene 3 lados iguales.", a: false },
  { q: "Un triángulo tiene 5 esquinas.", a: false },
  { q: "Una estrella de 5 puntas tiene 5 esquinas exteriores principales.", a: true },
  { q: "Un cubo tiene superficies curvas.", a: false },
  { q: "Las caras de un cubo son todos cuadrados.", a: true },
  { q: "Un círculo tiene 4 esquinas.", a: false },
  { q: "Un cuadrilátero siempre tiene 4 lados.", a: true },
  { q: "Un pentágono tiene 6 lados.", a: false },
  { q: "Un hexágono tiene 5 lados.", a: false },
  { q: "Un billete de papel tiene forma de rectángulo.", a: true },
  { q: "Una rebanada de pizza triangular tiene 3 lados.", a: true },
  { q: "Una señal de 'ALTO' de 8 lados es un octágono.", a: true },
  { q: "Un octágono tiene 8 lados.", a: true },
  { q: "Un octágono tiene 3 lados.", a: false },
  { q: "Un cuadrado tiene 4 lados iguales.", a: true },
  { q: "Un rectángulo tiene 5 vértices.", a: false },
  { q: "Los lados de un circulo son rectos.", a: false },
  { q: "Una caja de leche es un cuerpo tridimensional.", a: true },
  { q: "El número 10 es un número par.", a: true },
  { q: "El número 15 es mayor que 20.", a: false },
  { q: "100 es mayor que 99.", a: true },
  { q: "El número 7 es impar.", a: true },
  { q: "El número 0 es menor que 1.", a: true },
  { q: "El número 50 es igual a 5 decenas.", a: true },
  { q: "1 centena es igual a 100 unidades.", a: true },
  { q: "El número 45 tiene 4 decenas y 5 unidades.", a: true },
  { q: "El posterior de 19 es 20.", a: true },
  { q: "El anterior de 50 es 49.", a: true },
  { q: "El número 12 es un número impar.", a: false },
  { q: "El número 25 es menor que 15.", a: false },
  { q: "88 es mayor que 89.", a: false },
  { q: "El número 30 tiene 3 decenas y 0 unidades.", a: true },
  { q: "El número 9 es el número de un solo dígito más grande.", a: true },
  { q: "El número 100 es un número de dos dígitos.", a: false },
  { q: "El número 100 tiene tres dígitos.", a: true },
  { q: "En el número 73, el dígito 7 representa 70 unidades.", a: true },
  { q: "En el número 82, el dígito 2 es la decena.", a: false },
  { q: "Todos los números que terminan en 0 son pares.", a: true },
  { q: "Todos los números que terminan en 1 son pares.", a: false },
  { q: "El número 13 es par.", a: false },
  { q: "El número 24 es par.", a: true },
  { q: "El número 31 es impar.", a: true },
  { q: "El número 50 es mayor que 45.", a: true },
  { q: "El número 12 es menor que 8.", a: false },
  { q: "Entre 14 y 16 está el número 15.", a: true },
  { q: "El número anterior a 100 es 99.", a: true },
  { q: "El número posterior a 29 es 30.", a: true },
  { q: "El número 70 tiene 7 centenas.", a: false },
  { q: "2 decenas son iguales a 20 unidades.", a: true },
  { q: "5 decenas son iguales a 50 unidades.", a: true },
  { q: "10 decenas forman 100 unidades.", a: true },
  { q: "El número 200 es mayor que 150.", a: true },
  { q: "El número 300 es menor que 200.", a: false },
  { q: "El número 40 es menor que 14.", a: false },
  { q: "El número 66 está compuesto por 6 decenas y 6 unidades.", a: true },
  { q: "Si cuentas de 2 en 2 desde el 0: 0, 2, 4, 6, 8, todos son pares.", a: true },
  { q: "Si cuentas de 5 en 5 desde el 5: 5, 10, 15, 20... el siguiente es 25.", a: true },
  { q: "Si cuentas de 10 en 10 desde 10: 10, 20, 30... el siguiente es 35.", a: false },
  { q: "El número 1 es el primer número natural para contar.", a: true },
  { q: "El número 90 viene justo después de 89.", a: true },
  { q: "El número 101 viene justo antes de 100.", a: false },
  { q: "7 decenas significan 70.", a: true },
  { q: "3 centenas significan 300.", a: true },
  { q: "9 decenas y 9 unidades forman el número 99.", a: true },
  { q: "100 es el número más pequeño de 3 dígitos.", a: true },
  { q: "99 es el número más grande de 2 dígitos.", a: true },
  { q: "10 es el número más pequeño de 2 dígitos.", a: true },
  { q: "1 es un número de dos dígitos.", a: false },
  { q: "El número 17 es par.", a: false },
  { q: "El número 42 es par.", a: true },
  { q: "50 más 50 es igual a 100.", a: true },
  { q: "El doble de 5 es 10.", a: true },
  { q: "El doble de 4 es 8.", a: true },
  { q: "La mitad de 10 es 5.", a: true },
  { q: "La mitad de 20 es 10.", a: true },
  { q: "La mitad de 6 es 3.", a: true },
  { q: "El doble de 10 es 15.", a: false },
  { q: "La mitad de 14 es 7.", a: true },
  { q: "La mitad de 12 es 5.", a: false },
  { q: "5 más 5 es igual a 10.", a: true },
  { q: "10 más 20 es igual a 30.", a: true },
  { q: "15 más 5 es igual a 20.", a: true },
  { q: "8 más 2 es igual a 10.", a: true },
  { q: "7 más 3 es igual a 10.", a: true },
  { q: "6 más 4 es igual a 10.", a: true },
  { q: "9 más 1 es igual a 10.", a: true },
  { q: "12 más 3 es igual a 15.", a: true },
  { q: "20 más 20 es igual a 40.", a: true },
  { q: "30 más 30 es igual a 60.", a: true },
  { q: "40 más 10 es igual a 50.", a: true },
  { q: "100 más 100 es igual a 200.", a: true },
  { q: "25 más 25 es igual a 50.", a: true },
  { q: "14 más 6 es igual a 20.", a: true },
  { q: "11 más 11 es igual a 22.", a: true },
  { q: "13 más 7 es igual a 20.", a: true },
  { q: "50 más 10 es igual a 60.", a: true },
  { q: "70 más 30 es igual a 100.", a: true },
  { q: "80 más 20 es igual a 100.", a: true },
  { q: "90 más 10 es igual a 100.", a: true },
  { q: "15 más 15 es igual a 30.", a: true },
  { q: "16 más 4 es igual a 20.", a: true },
  { q: "18 más 2 es igual a 20.", a: true },
  { q: "22 más 3 es igual a 25.", a: true },
  { q: "35 más 5 es igual a 40.", a: true },
  { q: "45 más 5 es igual a 50.", a: true },
  { q: "10 más 0 es igual a 10.", a: true },
  { q: "0 más 7 es igual a 7.", a: true },
  { q: "100 más 0 es igual a 100.", a: true },
  { q: "5 más 4 es igual a 9.", a: true },
  { q: "6 más 6 es igual a 12.", a: true },
  { q: "7 más 7 es igual a 14.", a: true },
  { q: "8 más 8 es igual a 16.", a: true },
  { q: "9 más 9 es igual a 18.", a: true },
  { q: "4 más 4 es igual a 8.", a: true },
  { q: "3 más 3 es igual a 6.", a: true },
  { q: "5 más 5 es igual a 12.", a: false },
  { q: "10 más 10 es igual a 30.", a: false },
  { q: "8 más 2 es igual a 11.", a: false },
  { q: "15 más 5 es igual a 25.", a: false },
  { q: "20 más 30 es igual a 60.", a: false },
  { q: "7 más 4 es igual a 10.", a: false },
  { q: "9 más 3 es igual a 11.", a: false },
  { q: "12 más 5 es igual a 18.", a: false },
  { q: "50 más 50 es igual a 90.", a: false },
  { q: "14 más 4 es igual a 20.", a: false },
  { q: "6 más 5 es igual a 12.", a: false },
  { q: "30 más 40 es igual a 80.", a: false },
  { q: "100 más 50 es igual a 200.", a: false },
  { q: "17 más 3 es igual a 21.", a: false },
  { q: "25 más 10 es igual a 30.", a: false },
  { q: "8 más 8 es igual a 15.", a: false },
  { q: "7 más 7 es igual a 15.", a: false },
  { q: "9 más 9 es igual a 19.", a: false },
  { q: "6 más 6 es igual a 13.", a: false },
  { q: "4 más 5 es igual a 10.", a: false },
  { q: "13 más 3 es igual a 17.", a: false },
  { q: "40 más 40 es igual a 90.", a: false },
  { q: "60 más 20 es igual a 70.", a: false },
  { q: "15 más 10 es igual a 30.", a: false },
  { q: "11 más 9 es igual a 21.", a: false },
  { q: "18 más 2 es igual a 22.", a: false },
  { q: "33 más 3 es igual a 37.", a: false },
  { q: "45 más 5 es igual a 55.", a: false },
  { q: "80 más 10 es igual a 100.", a: false },
  { q: "50 más 20 es igual a 80.", a: false },
  { q: "12 más 12 es igual a 25.", a: false },
  { q: "13 más 13 es igual a 27.", a: false },
  { q: "20 más 5 es igual a 30.", a: false },
  { q: "30 más 5 es igual a 40.", a: false },
  { q: "Si a 5 le restas 5, te quedan 0.", a: true },
  { q: "Si a 5 le restas 5, te quedan 2.", a: false },
  { q: "10 menos 5 es igual a 5.", a: true },
  { q: "20 menos 10 es igual a 10.", a: true },
  { q: "15 menos 5 es igual a 10.", a: true },
  { q: "50 menos 10 es igual a 40.", a: true },
  { q: "100 menos 50 es igual a 50.", a: true },
  { q: "8 menos 3 es igual a 5.", a: true },
  { q: "9 menos 4 es igual a 5.", a: true },
  { q: "12 menos 2 es igual a 10.", a: true },
  { q: "15 menos 10 es igual a 5.", a: true },
  { q: "30 menos 10 es igual a 20.", a: true },
  { q: "40 menos 20 es igual a 20.", a: true },
  { q: "100 menos 1 es igual a 99.", a: true },
  { q: "20 menos 1 es igual a 19.", a: true },
  { q: "10 menos 1 es igual a 9.", a: true },
  { q: "7 menos 2 es igual a 5.", a: true },
  { q: "14 menos 4 es igual a 10.", a: true },
  { q: "18 menos 8 es igual a 10.", a: true },
  { q: "25 menos 5 es igual a 20.", a: true },
  { q: "35 menos 5 es igual a 30.", a: true },
  { q: "45 menos 5 es igual a 40.", a: true },
  { q: "60 menos 30 es igual a 30.", a: true },
  { q: "80 menos 40 es igual a 40.", a: true },
  { q: "90 menos 10 es igual a 80.", a: true },
  { q: "10 menos 0 es igual a 10.", a: true },
  { q: "15 menos 0 es igual a 15.", a: true },
  { q: "7 menos 7 es igual a 0.", a: true },
  { q: "50 menos 50 es igual a 0.", a: true },
  { q: "100 menos 100 es igual a 0.", a: true },
  { q: "16 menos 6 es igual a 10.", a: true },
  { q: "17 menos 7 es igual a 10.", a: true },
  { q: "19 menos 9 es igual a 10.", a: true },
  { q: "11 menos 1 es igual a 10.", a: true },
  { q: "13 menos 3 es igual a 10.", a: true },
  { q: "10 menos 3 es igual a 8.", a: false },
  { q: "20 menos 5 es igual a 10.", a: false },
  { q: "15 menos 3 es igual a 10.", a: false },
  { q: "50 menos 20 es igual a 20.", a: false },
  { q: "100 menos 10 es igual a 80.", a: false },
  { q: "9 menos 5 es igual a 3.", a: false },
  { q: "8 menos 4 es igual a 5.", a: false },
  { q: "14 menos 2 es igual a 10.", a: false },
  { q: "16 menos 4 es igual a 10.", a: false },
  { q: "30 menos 15 es igual a 20.", a: false },
  { q: "40 menos 10 es igual a 20.", a: false },
  { q: "100 menos 20 es igual a 70.", a: false },
  { q: "25 menos 10 es igual a 10.", a: false },
  { q: "18 menos 5 es igual a 12.", a: false },
  { q: "7 menos 3 es igual a 5.", a: false },
  { q: "12 menos 6 es igual a 7.", a: false },
  { q: "15 menos 8 es igual a 6.", a: false },
  { q: "20 menos 8 es igual a 11.", a: false },
  { q: "35 menos 10 es igual a 20.", a: false },
  { q: "50 menos 5 es igual a 40.", a: false },
  { q: "60 menos 20 es igual a 30.", a: false },
  { q: "70 menos 10 es igual a 50.", a: false },
  { q: "80 menos 30 es igual me 60.", a: false },
  { q: "90 menos 50 es igual a 30.", a: false },
  { q: "10 menos 10 es igual a 1.", a: false },
  { q: "5 menos 0 es igual a 0.", a: false },
  { q: "20 menos 0 es igual a 0.", a: false },
  { q: "100 menos 0 es igual a 0.", a: false },
  { q: "11 menos 2 es igual a 8.", a: false },
  { q: "13 menos 5 es igual a 7.", a: false },
  { q: "17 menos 8 es igual a 8.", a: false },
  { q: "19 menos 10 es igual a 8.", a: false },
  { q: "Una docena equivale a 12 unidades.", a: true },
  { q: "Una semana tiene 7 días.", a: true },
  { q: "Un año tiene 12 meses.", a: true },
  { q: "Un día tiene 24 horas.", a: true },
  { q: "Una hora tiene 60 minutos.", a: true },
  { q: "Un minuto tiene 60 segundos.", a: true },
  { q: "El reloj sirve para medir el tiempo.", a: true },
  { q: "Una semana tiene 10 días.", a: false },
  { q: "Un mes siempre tiene exactamente 10 días.", a: false },
  { q: "El billete de 10 dólares vale más que una moneda de 1 dólar.", a: true },
  { q: "Dos monedas de 50 centavos equivalen a 1 peso o dólar completo.", a: true },
  { q: "1 metro es más largo que 1 centímetro.", a: true },
  { q: "1 kilo de plumas pesa más que 1 kilo de hierro.", a: false },
  { q: "1 kilo de algodón y 1 kilo de piedra pesan exactamente lo mismo.", a: true },
  { q: "Un centímetro es más grande que un metro.", a: false },
  { q: "Una docena son 10 objetos.", a: false },
  { q: "Media docena equivale a 6 unidades.", a: true },
  { q: "Media docena equivale a 5 unidades.", a: false },
  { q: "Media hora son 30 minutos.", a: true },
  { q: "Media hora son 15 minutos.", a: false },
  { q: "Un cuarto de hora son 15 minutos.", a: true },
  { q: "El dinero en monedas y billetes sirve para pagar cosas.", a: true },
  { q: "Un billete de 20 vale más que un billete de 50.", a: false },
  { q: "Si tienes 3 monedas de 1 y te gastas 1, te quedan 2 monedas.", a: true },
  { q: "Si tienes 10 pesos y gastas 4 pesos, te quedan 6 pesos.", a: true },
  { q: "Si tienes 5 caramelos y te regalan 5 más, ahora tienes 10 caramelos.", a: true },
  { q: "Enero es el primer mes del año.", a: true },
  { q: "Diciembre es el último mes del año.", a: true },
  { q: "El sábado y el domingo suelen ser días del fin de semana.", a: true },
  { q: "Un año tiene 4 meses.", a: false },
  { q: "Un día tiene 12 horas en total.", a: false },
  { q: "Una hora dura menos que un minuto.", a: false },
  { q: "Un segundo dura más que una hora.", a: false },
  { q: "El termómetro sirve para medir la temperatura.", a: true },
  { q: "La regla escolar sirve para medir longitudes cortas.", a: true },
  { q: "La báscula o balanza sirve para medir la masa o peso.", a: true },
  { q: "Si tienes 15 lápices y regalas 5, te quedan 10 lápices.", a: true },
  { q: "Si lees 2 páginas hoy y 3 páginas mañana, habrás leído 5 páginas.", a: true },
  { q: "Una semana laboral de lunes a viernes tiene 5 días.", a: true },
  { q: "El mes de febrero es el mes más corto del año.", a: true },
  { q: "Si juntas 2 monedas de 10 centavos tienes 20 centavos.", a: true },
  { q: "Si juntas 5 monedas de 1 peso tienes 5 pesos.", a: true },
  { q: "100 centavos forman 1 unidad monetaria entera (un peso o dólar).", a: true },
  { q: "Un elefante pesa menos que un ratón.", a: false },
  { q: "Una jirafa es más alta que un gato.", a: true },
  { q: "Una regla de 30 cm es más corta que una de 15 cm.", a: false },
  { q: "Si caminas 10 pasos hacia adelante y 10 hacia atrás, quedas en el mismo lugar.", a: true },
  { q: "Si subes 3 escalones y luego subes 4 más, subiste 7 escalones en total.", a: true },
  { q: "Si tenías 8 globos y se reventaron 3, te quedan 5 globos.", a: true },
  { q: "Si tienes 10 manzanas y te comes las 10, te quedan 5 manzanas.", a: false }
];

// Generar dinámicamente más de 1000 preguntas adicionales
for (let i = 1; i <= 1000; i++) {
  const type = Math.floor(Math.random() * 3);
  let numA, numB, correctResult, isTrue, displayResult, qText;

  if (type === 0) 
  { // Suma
    numA = Math.floor(Math.random() * 20) + 1;
    numB = Math.floor(Math.random() * 20) + 1;
    correctResult = numA + numB;
    isTrue = Math.random() > 0.5;
    displayResult = isTrue ? correctResult : correctResult + (Math.random() > 0.5 ? 2 : -1);
    qText = `¿La suma de ${numA} + ${numB} es igual a ${displayResult}?`;
  } else if (type === 1) 
  { // Resta
    numA = Math.floor(Math.random() * 20) + 10;
    numB = Math.floor(Math.random() * numA) + 1;
    correctResult = numA - numB;
    isTrue = Math.random() > 0.5;
    displayResult = isTrue ? correctResult : Math.max(0, correctResult + (Math.random() > 0.5 ? 1 : -1));
    qText = `¿Si a ${numA} le restas ${numB}, el resultado es ${displayResult}?`;
  } 
  /* por ahora desabilito la multipicación
  else { // Multiplicación sencilla
    numA = Math.floor(Math.random() * 10) + 1;
    numB = Math.floor(Math.random() * 10) + 1;
    correctResult = numA * numB;
    isTrue = Math.random() > 0.5;
    displayResult = isTrue ? correctResult : correctResult + (Math.random() > 0.5 ? 3 : -2);
    qText = `¿La multiplicación de ${numA} x ${numB} es ${displayResult}?`;
  }
  */

  preguntasMatematicas.push({ q: qText, a: isTrue });
}
